import requests
from PIL import Image
import streamlit as st
from streamlit_lottie import st_lottie

title = "Nios Website"
icon = ":milky_way:"

st.set_page_config(page_title=title, page_icon=icon,layout="wide")

def load_lottieurl(url):
    r = requests.get(url)
    if r.status_code != 200:
        return None
    return r.json()



lottie_troll = load_lottieurl("https://assets6.lottiefiles.com/packages/lf20_ntvl70yw.json")
lottie_pepe = load_lottieurl("https://assets7.lottiefiles.com/packages/lf20_gCYYvh.json")

# ----Stuff----
with st.container():
    st.title(title)
    st.subheader("My fist try at creating a website lol")
    st.write("yeeet")

# ----Pepe----   
with st.container():
    st.write("---")
    left_column, right_column = st.columns(2)
    with left_column:
        st.header("Pepe lore")
        st.write("##")
        st.write(
            """
            Pepe is a cartoon frog character that became popular on the internet, particularly on 
            websites like 4chan and Reddit. The Pepe character started out as a benign meme used in 
            various contexts, such as to convey emotions like sadness or to express support for political 
            causes.

            However, over time, the Pepe character became associated with far-right political ideologies 
            and hate speech. This was largely due to the appropriation of the character by alt-right and
            white nationalist groups, who used variations of the character to spread racist and anti-Semitic 
            messages.

            As a result, the Anti-Defamation League has listed Pepe as a hate symbol. This has led to 
            widespread condemnation of the use of Pepe in hate speech and other extremist contexts.

            It is important to note that not all uses of Pepe are associated with hate speech or extremist 
            ideologies. However, due to the strong association of the character with these negative 
            contexts, many people consider the use of Pepe to be controversial and potentially offensive.

            [generated by AI]

        
            """)
        st.write("[Learn More >>](https://www.youtube.com/watch?v=dQw4w9WgXcQ)")

    with right_column:
        st_lottie(lottie_troll, height=300, key="troll")
        st_lottie(lottie_pepe, height=300, key="pepe")
       
# ----Interesting----    
with st.container():
    st.write("---")
    st.header("Interesting:")
    st.write("##")
    image_column, text_column = st.columns((1,2))

    with image_column:
        st.image("https://i.imgur.com/RE5JMwU.jpg")

    with text_column:
        st.subheader("Best Discord Servers")
        st.write("Dandelion Downtown:")
        st.markdown("   https://discord.gg/5eqaR6uA")
        st.write("Butterbrot89:")
        st.markdown("   https://discord.gg/REdzRzTJ")


    


